// SPDX-License-Identifier: MIT

mod catalog;
mod catalog_reobserve;
mod gateway;
mod json;
mod mapping;
mod projection;
mod protocol;
mod protocol_artifact;
mod protocol_artifact_coop_native;
mod protocol_artifact_coop_receipt_query;
#[path = "protocol_artifact_runtime_v2_hash.rs"]
mod protocol_artifact_hash;
mod protocol_artifact_runtime_map;
mod protocol_artifact_runtime_v2;
mod protocol_artifact_runtime_v3_gameplay;
mod protocol_artifact_runtime_v4_expert;
mod protocol_artifact_runtime_v4_expert_rest_action;
mod protocol_artifact_seeded_run;
mod receipt_query_json;
mod server;
mod transport;

pub use catalog::CHECKPOINT_REFERENCE_TOOL;
pub use catalog::COOP_RECEIPT_QUERY_TOOL;
pub use catalog::COOP_SYNCHRONIZATION_TOOL;
pub use catalog::{
    COOP_NATIVE_ACTION_TOOL, COOP_NATIVE_EFFECT_TOOL, COOP_NATIVE_OBSERVATION_TOOL,
    COOP_NATIVE_RECOVER_TOOL, COOP_NATIVE_REJOIN_TOOL, COOP_NATIVE_VOTE_TOOL,
};
pub use catalog::{
    CapabilityCatalog, DISPATCH_ACTION_TOOL, GET_STATE_TOOL, LEGAL_ACTIONS_TOOL, MAP_SNAPSHOT_TOOL,
    OBSERVE_TOOL, RECONCILE_ACTION_TOOL, RECOVER_TOOL, REOBSERVE_TOOL, SUBMIT_ACTION_TOOL,
    ToolCatalog, ToolDescriptor, WAIT_FOR_TRANSITION_TOOL,
};
pub use catalog::{EXPERT_ACTION_TOOL, EXPERT_RECONCILE_TOOL, EXPERT_STATE_TOOL};
pub use catalog::{EXPERT_REST_ACTION_TOOL, EXPERT_REST_RECONCILE_TOOL};
pub use catalog::{RECONCILE_SEEDED_RUN_TOOL, START_SEEDED_RUN_TOOL};
pub use catalog_reobserve::catalog_reobserve_body;
pub use gateway::{
    Correlation, GatewayAdapter, GatewayError, GatewayMethod, GatewayRequest, GatewayResponse,
};
pub use json::{JsonValue, parse_json};
pub use protocol::{
    INVALID_PARAMS, INVALID_REQUEST, METHOD_NOT_FOUND, PARSE_ERROR, RequestId, RpcError,
    RpcResponse,
};
pub use protocol_artifact::{
    ArtifactError, POC_ARTIFACT, POC_GENERATOR, POC_MAX_GENERATION, POC_MAX_SETTLED_EFFECTS,
    POC_MAX_UNITS, POC_PROTOCOL_VERSION, POC_SCHEMA_DIGEST, POC_SCHEMA_SOURCE, RUNTIME_ACTION_ID,
    RUNTIME_ARTIFACT, RUNTIME_GENERATOR, RUNTIME_MAX_GENERATION, RUNTIME_PROTOCOL_VERSION,
    RUNTIME_SCHEMA_DIGEST, RUNTIME_SCHEMA_SOURCE, verify_poc_artifact,
};
pub use protocol_artifact_coop_native::{
    COOP_NATIVE_ARTIFACT, COOP_NATIVE_GENERATOR, COOP_NATIVE_MAX_BODY_BYTES,
    COOP_NATIVE_MAX_GENERATION, COOP_NATIVE_PRODUCER_SCHEMA_DIGEST, COOP_NATIVE_PROFILE,
    COOP_NATIVE_PROTOCOL_VERSION, COOP_NATIVE_SCHEMA_DIGEST, COOP_NATIVE_SCHEMA_SOURCE,
    CoopNativeArtifactError, verify_coop_native_artifact,
};
pub use protocol_artifact_coop_receipt_query::{
    COOP_RECEIPT_QUERY_ARTIFACT, COOP_RECEIPT_QUERY_GENERATOR, COOP_RECEIPT_QUERY_MAX_BODY_BYTES,
    COOP_RECEIPT_QUERY_MAX_GENERATION, COOP_RECEIPT_QUERY_PROTOCOL_VERSION,
    COOP_RECEIPT_QUERY_SCHEMA_DIGEST, COOP_RECEIPT_QUERY_SCHEMA_SOURCE,
    CoopReceiptQueryArtifactError, verify_coop_receipt_query_artifact,
};
pub use protocol_artifact_runtime_map::{
    RUNTIME_MAP_V1_ARTIFACT, RUNTIME_MAP_V1_GENERATOR, RUNTIME_MAP_V1_MAX_BINDINGS,
    RUNTIME_MAP_V1_MAX_EDGES, RUNTIME_MAP_V1_MAX_GENERATION, RUNTIME_MAP_V1_MAX_HISTORY,
    RUNTIME_MAP_V1_MAX_MESSAGE_BYTES, RUNTIME_MAP_V1_MAX_NODES, RUNTIME_MAP_V1_PROTOCOL_VERSION,
    RUNTIME_MAP_V1_SCHEMA_DIGEST, RUNTIME_MAP_V1_SCHEMA_SOURCE, RuntimeMapArtifactError,
    verify_runtime_map_artifact,
};
pub use protocol_artifact_runtime_v2::{
    RUNTIME_V2_ACTION_ID, RUNTIME_V2_ARTIFACT, RUNTIME_V2_EFFECT_KIND, RUNTIME_V2_GENERATOR,
    RUNTIME_V2_MAX_GENERATION, RUNTIME_V2_MAX_TURN_INDEX, RUNTIME_V2_PLAYER_TURN_PHASE,
    RUNTIME_V2_PROTOCOL_VERSION, RUNTIME_V2_SCHEMA_DIGEST, RUNTIME_V2_SCHEMA_SOURCE,
    RuntimeV2ArtifactError, verify_runtime_v2_artifact,
};
pub use protocol_artifact_runtime_v3_gameplay::{
    RUNTIME_V3_GAMEPLAY_ARTIFACT, RUNTIME_V3_GAMEPLAY_GENERATOR,
    RUNTIME_V3_GAMEPLAY_MAX_GENERATION, RUNTIME_V3_GAMEPLAY_MAX_WAIT_MILLIS,
    RUNTIME_V3_GAMEPLAY_PROTOCOL_VERSION, RUNTIME_V3_GAMEPLAY_SCHEMA_DIGEST,
    RUNTIME_V3_GAMEPLAY_SCHEMA_SOURCE,
};
pub use protocol_artifact_runtime_v4_expert::{
    RUNTIME_V4_EXPERT_ACTION_ARTIFACT, RUNTIME_V4_EXPERT_ACTION_GENERATOR,
    RUNTIME_V4_EXPERT_ACTION_PROTOCOL_VERSION, RUNTIME_V4_EXPERT_ACTION_SCHEMA_DIGEST,
    RUNTIME_V4_EXPERT_ACTION_SCHEMA_SOURCE, RUNTIME_V4_EXPERT_ARTIFACT,
    RUNTIME_V4_EXPERT_GENERATOR, RUNTIME_V4_EXPERT_PROTOCOL_VERSION,
    RUNTIME_V4_EXPERT_SCHEMA_DIGEST, RUNTIME_V4_EXPERT_SCHEMA_SOURCE,
};
pub use protocol_artifact_runtime_v4_expert_rest_action::{
    RUNTIME_V4_EXPERT_REST_ACTION_ARTIFACT, RUNTIME_V4_EXPERT_REST_ACTION_EFFECT_WITNESS_VERSION,
    RUNTIME_V4_EXPERT_REST_ACTION_GENERATOR, RUNTIME_V4_EXPERT_REST_ACTION_MAX_GENERATION,
    RUNTIME_V4_EXPERT_REST_ACTION_MAX_IDENTITY_BYTES,
    RUNTIME_V4_EXPERT_REST_ACTION_MAX_SELECTOR_CHOICES, RUNTIME_V4_EXPERT_REST_ACTION_PROFILE,
    RUNTIME_V4_EXPERT_REST_ACTION_PROTOCOL_VERSION, RUNTIME_V4_EXPERT_REST_ACTION_SCHEMA_DIGEST,
    RUNTIME_V4_EXPERT_REST_ACTION_SCHEMA_SOURCE, RuntimeV4ExpertRestActionArtifactError,
    verify_runtime_v4_expert_rest_action_artifact,
};
pub use protocol_artifact_seeded_run::{
    SEEDED_RUN_ARTIFACT, SEEDED_RUN_EFFECT_KIND, SEEDED_RUN_GENERATOR, SEEDED_RUN_MAX_GENERATION,
    SEEDED_RUN_MAX_IDENTITY_BYTES, SEEDED_RUN_MAX_SEED_BYTES, SEEDED_RUN_PROTOCOL_VERSION,
    SEEDED_RUN_SCHEMA_DIGEST, SEEDED_RUN_SCHEMA_SOURCE, SeededRunArtifactError,
    verify_seeded_run_artifact,
};
pub use receipt_query_json::canonical_coop_receipt_query;
pub use server::{MCP_PROTOCOL_VERSION, McpServer, SERVER_NAME, SERVER_VERSION};
pub use transport::{FrameCodec, FrameError, MAX_FRAME_BYTES};

mod checkpoint_reference;
