// SPDX-License-Identifier: MIT

use crate::catalog::{
    GAME_INFORMATION_AVAILABILITY_TOOL, GAME_INFORMATION_CAPABILITIES_TOOL,
    GAME_INFORMATION_DETAIL_TOOL, GAME_INFORMATION_GET_TOOL, GAME_INFORMATION_LIST_TOOL,
    GAME_INFORMATION_SEARCH_TOOL,
};

pub(super) fn arguments(tool_name: &str) -> &'static [&'static str] {
    match tool_name {
        GAME_INFORMATION_CAPABILITIES_TOOL => {
            &["instance_id", "mcp_session_id", "lease_id", "lease_epoch"]
        }
        GAME_INFORMATION_LIST_TOOL | GAME_INFORMATION_SEARCH_TOOL => &[
            "instance_id",
            "mcp_session_id",
            "lease_id",
            "lease_epoch",
            "content_manifest_id",
            "locale",
            "visibility_scope",
            "entity_kind",
            "projection",
            "detail_level",
            "fields",
            "page_items",
            "item_bytes",
            "page_bytes",
            "text_bytes",
            "cursor",
            "display_name",
            "namespaced_ids",
            "definition_refs",
            "instance_ids",
        ],
        GAME_INFORMATION_GET_TOOL => &[
            "instance_id",
            "mcp_session_id",
            "lease_id",
            "lease_epoch",
            "content_manifest_id",
            "locale",
            "visibility_scope",
            "entity_kind",
            "projection",
            "detail_level",
            "fields",
            "page_items",
            "item_bytes",
            "page_bytes",
            "text_bytes",
            "cursor",
            "display_name",
            "namespaced_ids",
            "definition_refs",
            "instance_ids",
            "definition_ref",
        ],
        GAME_INFORMATION_DETAIL_TOOL => &[
            "instance_id",
            "mcp_session_id",
            "lease_id",
            "lease_epoch",
            "content_manifest_id",
            "locale",
            "visibility_scope",
            "entity_kind",
            "projection",
            "detail_level",
            "fields",
            "page_items",
            "item_bytes",
            "page_bytes",
            "text_bytes",
            "cursor",
            "display_name",
            "namespaced_ids",
            "definition_refs",
            "instance_ids",
            "definition_ref",
            "instance_ref",
            "snapshot_ref",
            "parent_observation",
        ],
        GAME_INFORMATION_AVAILABILITY_TOOL => &[
            "instance_id",
            "mcp_session_id",
            "lease_id",
            "lease_epoch",
            "content_manifest_id",
            "locale",
            "visibility_scope",
            "entity_kind",
            "projection",
            "detail_level",
            "fields",
            "page_items",
            "item_bytes",
            "page_bytes",
            "text_bytes",
            "cursor",
            "display_name",
            "namespaced_ids",
            "definition_refs",
            "instance_ids",
            "definition_ref",
            "instance_ref",
            "snapshot_ref",
            "parent_observation",
            "mode",
        ],
        _ => &[],
    }
}
