// SPDX-License-Identifier: MIT

use crate::json::JsonValue;

#[path = "recovery_frame_envelope.rs"]
mod envelope;
#[path = "recovery_frame_identity.rs"]
mod identity;
#[path = "recovery_frame_scalars.rs"]
mod scalars;
#[path = "recovery_frame_validation.rs"]
mod validation;

pub use identity::{utc_timestamp_now, uuid_v4};
pub use scalars::{valid_timestamp, valid_uuid, valid_uuid_v4};

/// The installed recovery-v1 frame contract every sideband frame carries.
pub const RECOVERY_CONTRACT: &str = "watchdog-recovery-v1";
/// SHA-256 of the installed recovery-v1 frame schema artifact.
pub const RECOVERY_SCHEMA_DIGEST: &str =
    "fb934d3157485aaf6e13e6ebbb213ec8a14c7fc6f5eeebc06b7a22c1f0009217";
/// Hard byte limit for one recovery frame, as the installed schema fixes it.
pub const RECOVERY_MAX_FRAME_BYTES: usize = 262_144;

/// The sideband is generated by the process that authenticates to the gateway as
/// the configured caller, so the frame actor is that caller in the gateway role.
const REQUEST_ROLE: &str = "gateway";
/// A recovery response is only ever produced by the authenticated gateway.
const RESPONSE_ROLE: &str = "gateway";

/// The two recovery operations this sideband forwards. The remaining fields of
/// the advertised watchdog surface belong to the runtime owner, not to MCP.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RecoveryOperation {
    Lookup,
    Reconcile,
}

impl RecoveryOperation {
    pub const ALL: [Self; 2] = [Self::Lookup, Self::Reconcile];

    #[must_use]
    pub const fn tool(self) -> &'static str {
        match self {
            Self::Lookup => "watchdog.operation_lookup",
            Self::Reconcile => "watchdog.operation_reconcile",
        }
    }

    #[must_use]
    pub fn from_tool(name: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|operation| operation.tool() == name)
    }

    /// The gateway route for the operation, without an instance prefix.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Lookup => "/v1/recovery/operation/lookup",
            Self::Reconcile => "/v1/recovery/operation/reconcile",
        }
    }

    #[must_use]
    pub fn from_path(path: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|operation| operation.path() == path)
    }

    #[must_use]
    pub const fn request_kind(self) -> &'static str {
        match self {
            Self::Lookup => "operation_lookup_request",
            Self::Reconcile => "operation_reconcile_request",
        }
    }

    #[must_use]
    pub const fn response_kind(self) -> &'static str {
        match self {
            Self::Lookup => "operation_lookup_response",
            Self::Reconcile => "operation_reconcile_response",
        }
    }

    /// The `x-sts2-recovery-capability` value the gateway route demands.
    #[must_use]
    pub const fn capability(self) -> &'static str {
        match self {
            Self::Lookup => "recovery_read",
            Self::Reconcile => "recovery_reconcile",
        }
    }
}

/// One built recovery request: the closed frame plus the correlation it carries
/// so the matching response can be bound to this exchange.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RecoveryRequest {
    pub correlation_id: String,
    pub frame: JsonValue,
}

/// Builds the closed request frame the gateway sideband route admits.
///
/// The principal is the configured gateway caller identity, never a value taken
/// from a tool argument, and the payload is forwarded verbatim: the caller owns
/// the recovery reference, so this layer validates its shape without rewriting
/// or re-deriving any field of it.
pub fn build_recovery_request(
    operation: RecoveryOperation,
    principal_id: &str,
    payload: &JsonValue,
) -> Result<RecoveryRequest, String> {
    if !valid_uuid(principal_id) {
        return Err(String::from(
            "recovery principal must be the configured gateway caller UUID",
        ));
    }
    let correlation_id = uuid_v4()?;
    let frame = JsonValue::object([
        ("contract".to_owned(), JsonValue::string(RECOVERY_CONTRACT)),
        (
            "schema_digest".to_owned(),
            JsonValue::string(RECOVERY_SCHEMA_DIGEST),
        ),
        ("message_id".to_owned(), JsonValue::string(uuid_v4()?)),
        (
            "correlation_id".to_owned(),
            JsonValue::string(correlation_id.as_str()),
        ),
        ("sent_at".to_owned(), JsonValue::string(utc_timestamp_now())),
        (
            "actor".to_owned(),
            JsonValue::object([
                ("principal_id".to_owned(), JsonValue::string(principal_id)),
                ("role".to_owned(), JsonValue::string(REQUEST_ROLE)),
            ]),
        ),
        (
            "auth".to_owned(),
            JsonValue::object([
                ("principal_id".to_owned(), JsonValue::string(principal_id)),
                (
                    "capability".to_owned(),
                    JsonValue::string(operation.capability()),
                ),
                ("proof".to_owned(), JsonValue::Null),
            ]),
        ),
        (
            "kind".to_owned(),
            JsonValue::string(operation.request_kind()),
        ),
        ("payload".to_owned(), payload.clone()),
    ]);
    validate_recovery_request(&frame, operation, principal_id)?;
    Ok(RecoveryRequest {
        correlation_id,
        frame,
    })
}

/// Validates one outgoing request frame against the closed gateway rules and
/// returns the correlation it carries.
pub fn validate_recovery_request(
    frame: &JsonValue,
    operation: RecoveryOperation,
    principal_id: &str,
) -> Result<String, String> {
    let correlation_id =
        envelope::validate_envelope(frame, operation.request_kind(), operation.capability())?;
    let object = frame.as_object().ok_or("recovery frame is not an object")?;
    if envelope::field_object(frame, "actor")
        .and_then(|actor| actor.get("principal_id"))
        .and_then(JsonValue::as_string)
        != Some(principal_id)
    {
        return Err(String::from(
            "recovery request actor is not the configured gateway principal",
        ));
    }
    validation::validate_request_payload(operation, object.get("payload"))?;
    Ok(correlation_id)
}

/// Validates one gateway response frame before its bytes are surfaced.
///
/// The frame is passed through verbatim: this check binds it to the exchange
/// that asked for it and rejects a body that is not a closed recovery response,
/// but it never re-derives or projects the operation record, because only the
/// runtime owner can cross-check that record against its own durable intent.
pub fn validate_recovery_response(
    frame: &JsonValue,
    operation: RecoveryOperation,
    correlation_id: &str,
) -> Result<(), String> {
    let echoed =
        envelope::validate_envelope(frame, operation.response_kind(), operation.capability())?;
    if echoed != correlation_id {
        return Err(String::from(
            "recovery response correlation does not echo the request",
        ));
    }
    let object = frame.as_object().ok_or("recovery frame is not an object")?;
    if envelope::field_object(frame, "actor")
        .and_then(|actor| actor.get("role"))
        .and_then(JsonValue::as_string)
        != Some(RESPONSE_ROLE)
    {
        return Err(String::from(
            "recovery response actor is not the authenticated gateway",
        ));
    }
    validation::validate_response_payload(operation, object.get("payload"))
}
