// SPDX-License-Identifier: MIT

use serde_json::{Value, json};
use sts2_mcp_server::{
    GatewayAdapter, GatewayError, GatewayRequest, GatewayResponse, McpServer, ToolCatalog,
    parse_json,
};

// Exact MIT protocol-owner response goldens for schema a76086d7..., not generated by this adapter.
const GOLDENS: [&str; 3] = [
    include_str!("runtime_v1_fixtures/state-response.json"),
    include_str!("runtime_v1_fixtures/action-accepted.json"),
    include_str!("runtime_v1_fixtures/action-rejected.json"),
];

struct FixedGateway(Value);
impl GatewayAdapter for FixedGateway {
    fn forward(&mut self, _: GatewayRequest) -> Result<GatewayResponse, GatewayError> {
        Ok(GatewayResponse {
            status: 200,
            body: parse_json(&self.0.to_string()).map_err(|_| GatewayError::MalformedResponse)?,
        })
    }
}

fn response(value: Value) -> Result<Value, Box<dyn std::error::Error>> {
    let action = value["kind"] == "action_response";
    let mut args = json!({"instance_id":"instance-1","mcp_session_id":"session-1"});
    if action {
        args["generation"] = json!(0);
        args["action_id"] = json!("show_runtime_probe");
    }
    let call = json!({"jsonrpc":"2.0","id":"shape-test","method":"tools/call",
        "params":{"name":if action {"submit_action"} else {"get_state"},"arguments":args}});
    let mut server = McpServer::with_catalog(FixedGateway(value), ToolCatalog::runtime_v1());
    Ok(serde_json::from_str(
        &server.handle_frame(&call.to_string()),
    )?)
}

#[test]
fn canonical_response_goldens_preserve_legacy_projection() -> Result<(), Box<dyn std::error::Error>>
{
    for (index, golden) in GOLDENS.iter().enumerate() {
        let original: Value = serde_json::from_str(golden)?;
        let result = response(original.clone())?;
        assert_eq!(result["result"]["isError"], json!(index == 2));
        let text = result["result"]["content"][0]["text"]
            .as_str()
            .ok_or("missing content")?;
        let projected: Value = serde_json::from_str(text)?;
        let mut expected = serde_json::Map::new();
        for key in [
            "kind",
            "generation",
            "observation",
            "action",
            "status",
            "error_code",
            "effect_witness",
        ] {
            if !original[key].is_null() {
                expected.insert(key.to_owned(), original[key].clone());
            }
        }
        assert_eq!(projected, Value::Object(expected));
    }
    Ok(())
}

#[test]
fn missing_or_extra_fields_fail_closed() -> Result<(), Box<dyn std::error::Error>> {
    for golden in GOLDENS {
        let original: Value = serde_json::from_str(golden)?;
        for key in original.as_object().ok_or("not object")?.keys() {
            let mut missing = original.clone();
            missing.as_object_mut().ok_or("not object")?.remove(key);
            assert_invalid(missing)?;
        }
        for pointer in [
            "",
            "/provenance",
            "/observation",
            "/action",
            "/effect_witness",
        ] {
            let mut extra = original.clone();
            if let Some(object) = extra.pointer_mut(pointer).and_then(Value::as_object_mut) {
                object.insert("unexpected".to_owned(), json!(true));
                assert_invalid(extra)?;
            }
        }
    }
    Ok(())
}

#[test]
fn inconsistent_status_and_witness_combinations_fail_closed()
-> Result<(), Box<dyn std::error::Error>> {
    let cases = [
        (0, "/status", json!("accepted")),
        (0, "/action", json!({"action_id":"show_runtime_probe"})),
        (0, "/error_code", json!("some_error")),
        (
            0,
            "/effect_witness",
            json!({"kind":"status_overlay_visible","generation":0}),
        ),
        (1, "/status", Value::Null),
        (1, "/status", json!("settled")),
        (1, "/effect_witness", Value::Null),
        (1, "/effect_witness/kind", json!("wrong")),
        (1, "/effect_witness/generation", json!(0)),
        (1, "/effect_witness/generation", json!(2)),
        (1, "/error_code", json!("some_error")),
        (1, "/action", Value::Null),
        (1, "/observation", Value::Null),
        (2, "/error_code", Value::Null),
        (2, "/error_code", json!("")),
        (
            2,
            "/effect_witness",
            json!({"kind":"status_overlay_visible","generation":1}),
        ),
    ];
    for (index, pointer, change) in cases {
        let mut value: Value = serde_json::from_str(GOLDENS[index])?;
        *value.pointer_mut(pointer).ok_or("missing pointer")? = change;
        assert_invalid(value)?;
    }
    Ok(())
}

fn assert_invalid(value: Value) -> Result<(), Box<dyn std::error::Error>> {
    let result = response(value)?;
    assert_eq!(result["result"]["isError"], json!(true));
    assert_eq!(
        result["result"]["content"][0]["text"],
        json!("gateway response has no valid allowlisted state or error projection")
    );
    Ok(())
}
